version: '2.1'

services:
  todo-service:
    image: todo-service
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
  redis-service:
    container_name: todo-redis-container
    image: redis:5.0.3
    restart: always
    ports:
      - 6380:6379
