version: '3'

services:
  todo-service:
    container_name: todo-service
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    links: ["redis-service"]
  redis-service:
    container_name: redis
    image: redis:5.0.3
    restart: always
    ports:
      - 6380:6379
